.travis.yml, package.json, pattern-single-panel-redux/src/store/store.js, pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js, scripts/build.js, scripts/lint.js
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Add Travis task and root level commands

pattern-virtuallist-preserving-focus/src/views/PatternList.js
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Fix VirtualList sample

pattern-expandablelist-object/src/views/MainPanel.js
PropType warnings are emitted in the console
Add a `key` to the array of objects
=> ENYO-5714: Fix missing key in sample

enact-all-samples/package.json, pattern-activity-panels-deep-linking/package.json, pattern-activity-panels-redux/package.json, pattern-activity-panels/package.json, pattern-dynamic-panel/package.json, pattern-expandablelist-object/package.json, pattern-layout/package.json, pattern-list-details-redux/package.json, pattern-list-details/package.json, pattern-locale-switching/package.json, pattern-ls2request/package.json, pattern-routable-panels/package.json, pattern-single-panel-redux/package.json, pattern-single-panel/package.json, pattern-video-player/package.json, pattern-virtualgridlist-api/package.json, pattern-virtuallist-preserving-focus/package.json, tutorial-hello-enact/package.json, tutorial-kitten-browser/package.json
Update dependencies from `next` to `^2.0.0`
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com
=> PLAT-76466: Update samples to pull 2.x branch

pattern-layout/src/App/App.js, pattern-layout/src/views/Details.js, pattern-list-details-redux/src/components/Content.js, pattern-list-details-redux/src/components/Nav/CountryButton.js, pattern-list-details/src/components/Content.js, pattern-list-details/src/components/Nav.js, pattern-video-player/src/views/MainPanel.js, pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js
Depends on enactjs/enact#2210
Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>
=> PLAT-76789: Replace small prop with size

pattern-single-panel-redux/src/App/App.js, pattern-single-panel-redux/src/components/PhotoPicker.js, pattern-single-panel-redux/src/components/SaveButton.js, pattern-single-panel-redux/src/components/SavedPopup.js, pattern-single-panel-redux/src/components/componentStyles.module.less, pattern-single-panel-redux/src/containers/FooterContainer.js, pattern-single-panel-redux/src/containers/containerStyles.module.less, pattern-single-panel-redux/src/views/MainPanel.js, pattern-single-panel-redux/src/views/MainPanel.module.less, pattern-single-panel/src/App/App.js, pattern-single-panel/src/components/ProfilePhotoPicker.js, pattern-single-panel/src/components/ProfilePhotoPicker.module.less, pattern-single-panel/src/components/SaveButton.js, pattern-single-panel/src/components/SaveButton.module.less, pattern-single-panel/src/views/MainPanel.js
Changed the layout for `pattern-single-panel` and `pattern-single-panel-redux` to let the `Slider` have width.
=> ENYO-5969: samples: pattern-single-panel Slider has no width

pattern-list-details-redux/src/App/App.js, pattern-list-details-redux/src/components/Content.js, pattern-list-details-redux/src/components/Content.module.less, pattern-list-details-redux/src/components/Nav/CountryButton.js, pattern-list-details-redux/src/components/Nav/Nav.js, pattern-list-details-redux/src/components/Nav/Nav.module.less, pattern-list-details-redux/src/components/SideBar/CityItem.js, pattern-list-details-redux/src/components/SideBar/SideBar.js, pattern-list-details-redux/src/components/SideBar/SideBar.module.less, pattern-list-details-redux/src/containers/SideBarContainer.js, pattern-list-details-redux/src/reducers/rootReducer.js, pattern-list-details-redux/src/views/Body.js, pattern-list-details-redux/src/views/Body.module.less, pattern-list-details-redux/src/views/MainView.js
Greatly simplified pattern through refactoring.  🏭🏭 :sogood:
=> ENYO-5968: Cleanup and refactor pattern-list-details-redux

enact-all-samples/package.json, my-theme-app/package.json, pattern-activity-panels-deep-linking/package.json, pattern-activity-panels-redux/package.json, pattern-activity-panels/package.json, pattern-analytics-webostv/package.json, pattern-analytics/package.json, pattern-dynamic-panel/package.json, pattern-expandablelist-object/package.json, pattern-layout/package.json, pattern-list-details-redux/package.json, pattern-list-details/package.json, pattern-locale-switching/package.json, pattern-ls2request/package.json, pattern-routable-panels/package.json, pattern-single-panel-redux/package.json, pattern-single-panel/package.json, pattern-video-player/package.json, pattern-virtualgridlist-api/package.json, pattern-virtuallist-preserving-focus/package.json, tutorial-hello-enact/package.json, tutorial-kitten-browser/package.json
Adds `ilib` dependency.
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>
=> PLAT-81548: Update other apps/tools for iLib relocation

tutorial-hello-enact/package.json, tutorial-hello-enact/src/App/App.js, tutorial-hello-enact/src/index.js
Enact-DCO-1.0-Signed-off-by: Yunho Lee (yunho2.lee@lge.com)
Change theme from moonstone to sandstone.
=> PLAT-129114: Update "Hello, Enact" source code

agate/all-samples/src/index.js, moonstone/all-samples/src/index.js, sandstone/all-samples/src/index.js
Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
Avoid console error (React does not recognize the ~ prop on a DOM element ... )
Console error occured because route props(staticContext) were passed to the components 
WRN-3523
=> WRN-3523: Fix console error

sandstone/custom-skin/src/App/App.module.less, sandstone/custom-skin/src/components/OutputField.js, sandstone/custom-skin/src/components/SingleField.js, sandstone/custom-skin/src/components/SingleField.module.less, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/components/TripleField.module.less, sandstone/custom-skin/src/views/MainPanel.js
Created the UI components for the custom skin app
WRN-7346
=> WRN-7346: Create CSS variables UI panel for the custom skin project.

sandstone/custom-skin/src/components/SingleField.js, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/views/MainPanel.js
Created a state that can be influenced by the variables we introduce via the input fields.
WRN-7347
=> WRN-7347:CSS variables manual editing.

sandstone/custom-skin/src/components/AutoPopup.js, sandstone/custom-skin/src/components/ColorFields.js, sandstone/custom-skin/src/components/SingleField.js, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/views/MainPanel.js
Create a text area to inspect and get the CSS values generated by the program
WRN-7348
=> WRN-7348: Create a text area to get the CSS values from.

sandstone/custom-skin/src/components/AutoPopup.js, sandstone/custom-skin/src/components/SingleField.module.less, sandstone/custom-skin/src/utils.js, sandstone/custom-skin/src/views/MainPanel.js
=> WRN-7349: UI Auto mode.

sandstone/custom-skin/src/components/ColorFields.js, sandstone/custom-skin/src/components/NameField.js, sandstone/custom-skin/src/components/NameField.module.less, sandstone/custom-skin/src/components/OutputField.js, sandstone/custom-skin/src/components/SingleField.js, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/utils.js, sandstone/custom-skin/src/views/MainPanel.js
Added field for skin name
WRN-8022
=> WRN-8022: Add Skin Name

sandstone/custom-skin/src/components/ImportSkin.js, sandstone/custom-skin/src/components/NameField.js, sandstone/custom-skin/src/components/OutputField.js, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/utils.js, sandstone/custom-skin/src/views/MainPanel.js
Added a button to import a skin that conforms to our standards.
WRN-8023
=> WRN-8023: Import custom skin.

sandstone/custom-skin/src/components/ColorFields.js, sandstone/custom-skin/src/components/SingleField.js, sandstone/custom-skin/src/components/TripleField.js, sandstone/custom-skin/src/utils.js, sandstone/custom-skin/src/views/MainPanel.js
This is just a merge to update custom-skin with the latest features.
=> WRN-8024: Progress merge.

sandstone/all-samples/package.json, sandstone/pattern-analytics-webostv/package.json, sandstone/pattern-dynamic-panel/package.json, sandstone/pattern-layout/package.json, sandstone/pattern-locale-switching/package.json, sandstone/pattern-routable-panels/package.json, sandstone/pattern-single-panel-redux/package.json, sandstone/pattern-single-panel/package.json, sandstone/pattern-video-player/package.json, sandstone/pattern-virtualgridlist-api/package.json, sandstone/pattern-virtuallist-preserving-focus/package.json
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
=> WRN-9396: Samples: Samples are displayed at the wrong resolution

sandstone/custom-skin/src/common/styles.module.less, sandstone/custom-skin/src/components/AutoPopup/AutoPopup.js, sandstone/custom-skin/src/components/ColorFields/ColorFields.js, sandstone/custom-skin/src/components/NameField/NameField.js, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/components/OutputField/OutputField.module.less, sandstone/custom-skin/src/components/SingleField/SingleField.js, sandstone/custom-skin/src/components/SingleField/SingleField.module.less, sandstone/custom-skin/src/components/TripleField/TripleField.js, sandstone/custom-skin/src/components/TripleField/TripleField.module.less, sandstone/custom-skin/src/views/MainPanel.js, sandstone/custom-skin/src/views/MainPanel.module.less
Made skin apply only to Preview Area.
WRN-11824
=> WRN-11824: Custom skin css generator app - Make skin apply only to Preview Area

sandstone/custom-skin/package.json, sandstone/custom-skin/src/common/styles.module.less, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/views/MainPanel.js
Added the Reset Skin button and did some minor fixes.
WRN-12775
=> WRN-12775: Add a reset skin button. 

sandstone/tutorial-kitten-browser/src/components/Kitten/Kitten.js
Update Kitten Browser tutorial app and documentation to work with 'ok' key on kitten items
WRN-12851
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>
=> WRN-12851: Update kitten items to work with OK key

sandstone/custom-skin/src/views/MainPanel.js, sandstone/custom-skin/src/views/MainPanel.module.less
Preview section has a fixed position in respect to scrolling
=> WRN-12938: Make Live Demo fixed in respect to scrolling

sandstone/all-samples/src/components/SampleItem/SampleItem.js, sandstone/pattern-layout/src/App/App.js, sandstone/pattern-locale-switching/src/components/LocaleSwitch/LocaleSwitch.js, sandstone/pattern-single-panel-redux/src/components/SavedPopup.js, sandstone/pattern-single-panel/src/components/ProfilePhotoPicker.js, sandstone/pattern-single-panel/src/components/SaveButton.js, sandstone/pattern-video-player/src/App/App.js, sandstone/pattern-video-player/src/App/videos.js, sandstone/pattern-virtualgridlist-api/src/components/ImageList/ImageList.js, sandstone/pattern-virtualgridlist-api/src/views/MainView.js, sandstone/pattern-virtuallist-preserving-focus/src/views/PatternList.js, sandstone/pattern-virtuallist-preserving-focus/src/views/PatternList.module.less, ui/all-samples/src/components/SampleItem/SampleItem.js, ui/pattern-list-details/src/views/Body.js, ui/pattern-list-details/src/views/MainView.js, ui/pattern-ls2request/src/App/App.js
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
- Update class components of sandstone and ui to Hooks
=> WRN-795 : Update sandstone samples with new React style APIs

sandstone/custom-skin/src/components/ColorPicker/ColorPicker.js, sandstone/custom-skin/src/components/ColorPicker/ColorPicker.module.less, sandstone/custom-skin/src/components/SingleField/SingleField.js, sandstone/custom-skin/src/components/TripleField/TripleField.js, sandstone/custom-skin/src/utils.js
Created a new HSL ColorPicker to work with 5 way. Fixed a bug for TipleField. 
WRN-12940
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
=> WRN-12940: Handle 5-way nav with color pickers.

sandstone/custom-skin/src/App/App.module.less, sandstone/custom-skin/src/common/styles.module.less, sandstone/custom-skin/src/components/AutoPopup/AutoPopup.js, sandstone/custom-skin/src/components/ColorPicker/ColorPicker.js, sandstone/custom-skin/src/components/ColorPicker/ColorPicker.module.less, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.module.less, sandstone/custom-skin/src/components/NameField/NameField.js, sandstone/custom-skin/src/components/NameField/NameField.module.less, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/components/OutputField/OutputField.module.less, sandstone/custom-skin/src/components/SingleField/SingleField.js, sandstone/custom-skin/src/components/SingleField/SingleField.module.less, sandstone/custom-skin/src/components/TripleField/TripleField.js, sandstone/custom-skin/src/components/TripleField/TripleField.module.less, sandstone/custom-skin/src/views/MainPanel.js, sandstone/custom-skin/src/views/MainPanel.module.less
Added some media queries so the app does not break its layout on smaller resolution
=> WRN-12943: Improve window size changes

sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/components/OutputField/OutputField.module.less, sandstone/custom-skin/src/views/MainPanel.js
Added 'Back to top' button which scrolls the page to the top
=> WRN-15495: Add "Back to top" button

sandstone/custom-skin/src/components/ColorPicker/ColorPicker.js, sandstone/custom-skin/src/components/ColorPicker/ColorPicker.module.less, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/components/OutputField/OutputField.module.less, sandstone/custom-skin/src/components/SingleField/SingleField.js, sandstone/custom-skin/src/components/TripleField/TripleField.js, sandstone/custom-skin/src/views/MainPanel.js
Added HTML color picker when custom skin app is run on PC or Mac. When the app si run on webOS, the custom slider color picker is used.
=> WRN-15496: Add HTML Color Picker for PC/Mac

sandstone/custom-skin/src/components/ColorPicker/ColorPicker.js, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/views/MainPanel.js
Color Picker bug fix and platform specific features.
WRN-17860
=> WRN-17860: Fix color picker slider not matching with the number.

sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/constants.js, sandstone/custom-skin/src/views/MainPanel.js
Fixed some known bugs and made some modifications to naming based on SWP suggestions
=> WRN-18823: Fix bugs and change colors list names

sandstone/react-18/src/views/Batching/BatchedAssign.js, sandstone/react-18/src/views/Batching/Batching.js, sandstone/react-18/src/views/Batching/NotBatchedAssign.js
Created an example that shows the difference between the automatic batching of react 18 and the non batched approach used by older versions.
WRN-18233
=> WRN-18233: Create sample page for Batching.

sandstone/react-18/src/views/UseTransition/Content.js, sandstone/react-18/src/views/UseTransition/FakeApi.js, sandstone/react-18/src/views/UseTransition/UseTransition.js, sandstone/react-18/src/views/UseTransition/UseTransition.module.less
Added sample for useTransition
WRN-18227
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-18226: Added sample for useTransition

agate/pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js, agate/pattern-virtualgridlist-api/src/reducers/index.js, moonstone/pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js, moonstone/pattern-virtualgridlist-api/src/reducers/index.js, sandstone/pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js, sandstone/pattern-virtualgridlist-api/src/reducers/index.js
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com
Changed image service.
=> WRN-17786: Changed Placehold.it Image service

sandstone/pattern-react18-new/package.json
Added Sample for React 18 Features
WRN-19202
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-19202: Added Sample for React 18 Features

sandstone/pattern-single-panel/package.json
fix unit test fail 
`enact test --watch` test fail
FAIL  src/components/tests/SaveButton-specs.js
● Console
console.error
Error: Uncaught [Error: Unable to find node on an unmounted component.]
Need to update @enact package libraries for react18
=> Fix unit test fail (update dependencies)

moonstone/all-samples/package.json, moonstone/pattern-activity-panels-deep-linking/package.json, moonstone/pattern-activity-panels-redux/package.json, moonstone/pattern-locale-switching/package.json, moonstone/pattern-locale-switching/src/components/LocaleSwitch/LocaleSwitch.js, moonstone/pattern-routable-panels/package.json, moonstone/pattern-single-panel-redux/package.json, moonstone/pattern-single-panel/package.json, moonstone/pattern-virtualgridlist-api/package.json, moonstone/pattern-virtuallist-preserving-focus/package.json
Updated redux related dependencies for moonstone samples
WRO-3722
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRO-3722: Updated redux related dependencies for moonstone samples

sandstone/custom-skin/src/utils.js, scripts/bootstrap.js, scripts/build.js, scripts/lint.js, scripts/test.js
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Lint fixes
WRO-4059
=> WRO-4059: Fix lint warnings from updated lint rules.

tutorial-typescript/package.json, tutorial-typescript/src/App/App.tsx, tutorial-typescript/src/components/Counter/Counter.tsx, tutorial-typescript/src/index.tsx, tutorial-typescript/src/views/MainPanel.tsx, tutorial-typescript/tslint.json
Updated @enact/samples/tutorial-typescript to use sandstone instead of moonstone
WRO-4821
Enact-DCO-1.0-Signed-off-by: Clapou George-Vladut(vladut.clapou@lgepartner.com)
=> Feature/WRO-4821: TypeScript: Update tutorial typescript sample

tutorial-typescript/src/components/Counter/Counter.tsx, tutorial-typescript/src/index.tsx, tutorial-typescript/src/views/MainPanel.tsx
Updated @enact/samples/tutorial-typescript code to sync with the docs repo.
WRO-713
Enact-DCO-1.0-Signed-off-by: Clapou George-Vladut(vladut.clapou@lgepartner.com)
=> Feature/WRO-713: TypeScript: Example code of tutorial typescript is not working

tutorial-typescript/src/components/Counter/Counter.tsx
I found two warnings to be fixed in the tutorial-typescript sample.
Fixed to pass enact linting in strict mode
WRO-713
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek (sc.baek@lge.com)
=> WRO-713: Fix eslint warnings in strict mode

sandstone/custom-skin/src/common/styles.module.less, sandstone/custom-skin/src/components/ColorFields/ColorFields.js, sandstone/custom-skin/src/components/ColorPicker/ColorPicker.module.less, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.module.less, sandstone/custom-skin/src/components/NameField/NameField.module.less, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/components/OutputField/OutputField.module.less, sandstone/custom-skin/src/components/SingleField/SingleField.module.less, sandstone/custom-skin/src/components/TripleField/TripleField.module.less, sandstone/custom-skin/src/views/MainPanel.js, sandstone/custom-skin/src/views/MainPanel.module.less
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Changed the variables that overwrite the skin ones to cover the correct css attributes.
WRO-11352
=> WRO-11352: CustomSkin generator: Fix custom skin components colors.

agate/pattern-virtualgridlist-api/src/views/MainView.js, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js, sandstone/custom-skin/src/components/OutputField/OutputField.js, sandstone/custom-skin/src/utils.js, sandstone/custom-skin/src/views/MainPanel.js, sandstone/pattern-react18-new/src/views/Suspense/SamplePage.js, sandstone/pattern-react18-new/src/views/Suspense/SkeletonPage.js, sandstone/pattern-react18-new/src/views/UseTransition/Content.js, sandstone/pattern-react18-new/src/views/UseTransition/UseTransition.js, scripts/lint.js
Update lint.js to apply lint options and fix the lint warnings.
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)
=> WRO-12570: Update lint.js to apply lint options

sandstone/custom-skin/package.json, sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js, sandstone/custom-skin/src/utils.js, sandstone/pattern-react18-new/package.json, sandstone/pattern-react18-new/src/views/Suspense/SamplePage.js, sandstone/pattern-react18-new/src/views/UseTransition/Content.js
Some samples did not have the correct eslint configuration.
Applied the correct lint option to samples and fixed eslint warnings that occured after this change.
Due to some changes made in the configuration of the eslint, new warnings occured that were fixed in this PR as well.
(e.g ImportSkins.js, utils.js, SamplePage.js, Content.js)
WRP-4194
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-4194: Apply correct lint option to samples

agate/all-samples/package.json, agate/pattern-dynamic-panel/package.json, agate/pattern-layout/package.json, agate/pattern-locale-switching/package.json, agate/pattern-single-panel-redux/package.json, agate/pattern-single-panel/package.json, agate/pattern-virtualgridlist-api/package.json, agate/pattern-virtuallist-preserving-focus/package.json, moonstone/all-samples/package.json, moonstone/pattern-activity-panels-deep-linking/package.json, moonstone/pattern-activity-panels-redux/package.json, moonstone/pattern-activity-panels/package.json, moonstone/pattern-analytics-webostv/package-lock.json, moonstone/pattern-analytics-webostv/package.json, moonstone/pattern-dynamic-panel/package.json, moonstone/pattern-expandablelist-object/package.json, moonstone/pattern-layout/package.json, moonstone/pattern-locale-switching/package.json, moonstone/pattern-routable-panels/package.json, moonstone/pattern-single-panel-redux/package.json, moonstone/pattern-single-panel/package.json, moonstone/pattern-video-player/package.json, moonstone/pattern-virtualgridlist-api/package.json, moonstone/pattern-virtuallist-preserving-focus/package.json, moonstone/tutorial-hello-enact/package.json, moonstone/tutorial-kitten-browser/package.json, sandstone/all-samples/package.json, tutorial-typescript/package.json, ui/all-samples/package.json
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Updated package dependencies to fix security vulnerabilities.
WRP-3074
=> WRP-3074: Update package dependencies to fix security vulnerabilities

.travis.yml, agate/all-samples/package.json, agate/pattern-layout/package.json, moonstone/all-samples/package.json, moonstone/pattern-layout/package.json, sandstone/all-samples/package.json, sandstone/pattern-layout/package.json, ui/all-samples/package.json
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Updated `query-string` package dependency to latest version
Removed `query-string` dependency from ui/all-samples since it has no usage
Updated `query-string` package dependency to latest version
Removed `query-string` dependency from ui/all-samples since it has no usage
`query-string` v8.1.0 has major breaking changes, but they don't affect our code:
- `query-string` is now ESM
- minimum node …
=> WRP-14788: Update query-string dependency to latest version

tutorial-typescript/package.json, tutorial-typescript/src/index.tsx
Update typescript dependency for samples from v. ^4.9.5 to v. ^5.0.4
samples/tutorial-typescript now uses the latest typescript version.
There were no breaking changes affecting enact app https://github.com/microsoft/TypeScript/releases
WRP-15615
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-15615: Update typescript dependency to the latest major version.

sandstone/tutorial-kitten-browser/src/App/App.js, sandstone/tutorial-kitten-browser/src/App/App.module.less, sandstone/tutorial-kitten-browser/src/components/Kitten/Kitten.js, sandstone/tutorial-kitten-browser/src/views/Detail.js
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)
Update sample code to match with [enactjs/docs/pull/228](https://github.com/enactjs/docs/pull/228)
=> WRP-26628: Kitten browser: Update State and Data management sections

sandstone/feature-dynamic-theme-generator/README.md, sandstone/feature-dynamic-theme-generator/src/App/App.js, sandstone/feature-dynamic-theme-generator/src/components/ColorPicker/ColorPicker.js, sandstone/feature-dynamic-theme-generator/src/hooks/dynamicColor.js, sandstone/feature-dynamic-theme-generator/src/hooks/generateStylesheet.js, sandstone/feature-dynamic-theme-generator/src/hooks/useLinearColor.js, sandstone/feature-dynamic-theme-generator/src/hooks/utils.js, sandstone/feature-dynamic-theme-generator/src/views/CustomizePanel/CustomizePanel.module.less, sandstone/feature-dynamic-theme-generator/src/views/MainView/MainView.js, sandstone/feature-dynamic-theme-generator/src/views/MainView/MainView.module.less, sandstone/feature-dynamic-theme-generator/src/views/PresetPanel/PresetPanel.js, sandstone/feature-dynamic-theme-generator/src/views/PresetPanel/PresetPanel.module.less
Custom colors sample needs documentation.
Added jsdocs, comments within the code and a readme file.
WRP-28251
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com
=> WRP-28251: Create documentation for dynamic color mode

sandstone/pattern-ls2request-custom-colors/src/lunaCalls/getSystemSettings.js, sandstone/pattern-ls2request-custom-colors/src/views/MainView/MainView.js, sandstone/pattern-ls2request-custom-colors/src/views/ShowcaseView/ShowcaseView.js
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Added luna calls to fetch data from `theme` key
WRQ-1937
=> QWR-1937: pattern-ls2request-custom-colors - add Luna Services

agate/pattern-single-panel/src/components/ProfilePhotoPicker.js, agate/pattern-single-panel/src/components/tests/ProfilePhotoPicker-specs.js, agate/pattern-single-panel/src/components/tests/SaveButton-specs.js, moonstone/pattern-single-panel/src/components/ProfilePhotoPicker.js, moonstone/pattern-single-panel/src/components/tests/ProfilePhotoPicker-specs.js, moonstone/pattern-single-panel/src/components/tests/SaveButton-specs.js, moonstone/tutorial-kitten-browser/src/components/Kitten/tests/Kitten-specs.js, sandstone/pattern-single-panel/src/components/ProfilePhotoPicker.js, sandstone/pattern-single-panel/src/components/tests/ProfilePhotoPicker-specs.js, sandstone/pattern-single-panel/src/components/tests/SaveButton-specs.js, sandstone/tutorial-kitten-browser/src/components/Kitten/tests/Kitten-specs.js, ui/pattern-list-details/src/components/Content.js, ui/pattern-list-details/src/components/tests/Content-specs.js, ui/pattern-list-details/src/components/tests/Nav-specs.js, ui/pattern-list-details/src/components/tests/SideBar-specs.js
Updated unit tests to work with `@testing-library/user-event v14`
In order to make all the unit tests pass and samples work, it was needed to change the path for the imported images
WRQ-165
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
=> WRQ-165: Updated unit tests to work with @testing-library/user-event v14
